unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!mkdir -p ' .data_dir.'/autoload/'
  silent execute '!wget -O '.data_dir.'/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

Plug 'arcticicestudio/nord-vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'vim-airline/vim-airline'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'yuezk/vim-js'
Plug 'maxmellon/vim-jsx-pretty'
Plug 'vim-scripts/DoxygenToolkit.vim'

if (executable("node"))
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  source ~/.vim/coc-config.vim
endif

call plug#end()

" coc.nvim
let g:coc_global_extensions = ['coc-json', 'coc-pairs', 'coc-tsserver', 'coc-html', 'coc-css', 'coc-emmet', 'coc-clangd', 'coc-vimlsp', 'coc-sh']

autocmd BufNewFile,BufRead *.tsx setlocal filetype=typescriptreact
autocmd BufNewFile,BufRead *.jsx setlocal filetype=javascriptreact

" Theme
set termguicolors
color catppuccin_macchiato

" Settings
set number
set relativenumber
filetype plugin indent on

" Indentation
set shiftwidth=4 smarttab
set expandtab
set tabstop=4 softtabstop=0

" Bell
set visualbell hidden
set t_vb=

" Mappings
vnoremap <C-y> "+y| " Copy to system clipboard
noremap ; :
noremap \rs :%s/\v\s+$//g<CR>g`'| " Remove trailing whitespace

function s:source(file)
    if !empty(glob(a:file))
        exec "source " . a:file
    endif
endfunction

call s:source("~/.vim/functions.vim")
