#!/usr/bin/env bash

log-msg() {
	[[ -z "$LOG_FILE" ]] && return 0

	echo -e "($(echo $$)) [$(date +'%F %r')] $@" >> "$LOG_FILE"
}

tmux-get-pane-id() {
	tmux display-message -p "#{pane_id}"
}

tmux-get-ssh-pane-pid() {
	local target_id=$1
	tmux show-environment SSH_PID_$target_id 2> /dev/null | grep -Po '(?<==).+'
}

tmux-set-ssh-pane-pid() {
	local target_id=$1
	local pid=$2

	tmux set-environment SSH_PID_$target_id $pid
}

# If the pane is ssh, output the ssh command. Otherwise, output nothing.
tmux-get-pane-cmd() {
	local pane_id="$1"
	local pane_pid=

	if [[ -n "$pane_id" ]]; then
		pane_id="-t $1"
	fi

	pane_pid=$(tmux display-message $pane_id -p "#{pane_pid}")
	[[ -z "$pane_pid" ]] && return 0

	ps -o command= -g $pane_pid | grep -P '^ssh' | sed -E 's/ -t .*bash//'
}

# Unsets ssh pids belonging to pane ids that don't have active ssh sessions
clean-ssh-pane-pids() {
	local active_pane_ids=
	local ssh_pid_pane_ids=
	local pane_ids=

	active_pane_ids="$(tmux list-panes | grep -Po '%\d+')"

	ssh_pid_pane_ids="$(tmux show-env | tr ' ' '\n' | cut -d '=' -f 1 | \
		grep -Po '(?<=SSH_PID_)%\d+')"

	pane_ids=$(tr ' ' '\n' <<< "$active_pane_ids $ssh_pid_pane_ids" | sort -u | tr '\n' ' ')

	for id in $pane_ids; do
		local cmd=$(tmux-get-pane-cmd $id);

		if [[ -z "$cmd" ]] || ! grep ssh <<< "$cmd" &> /dev/null; then
			log-msg "Unsetting SSH_PID_$id"
			tmux set-environment -u SSH_PID_$id
		fi
	done
}

# Sets the ssh pid for the newly spawned pane.
# Sets the previous pane's ssh pid if none was set (typically the first ssh session).
set-pane-pids() {
	local ssh_pid="$1"
	local prev_pane_id="$2"
	local pane_id="$3"
	local identifier="$4"

	log-msg "pane_id=$pane_id, prev_pane_id=$prev_pane_id, identifier=$identifier"

	local pids=()
	local pid_items=

	while [[ -z "$pid_items" ]] && \
		tmux list-panes | grep -E "$pane_id(\$| )" &> /dev/null
	do
		log-msg "[$$] $pane_id: searching for $identifier"
		pid_items=$(tmux capture-pane -p -t $pane_id | grep -Po "(?<=$identifier: ).*")
		sleep 0.1
	done

	pids=($pid_items)

	tmux-set-ssh-pane-pid $pane_id ${pids[0]}

	# When the ssh pane doesn't have a pid set
	if [[ "$ssh_pid" == "\$PREV_PID" ]]; then
		tmux-set-ssh-pane-pid $prev_pane_id ${pids[1]}
	fi
}

tmux-ssh-split() {
	local split_cmd="$1"
	local direction="$2"
	local ssh_cmd="$3"

	if [[ "$split_cmd" == "new-window" ]]; then
		direction=""
	fi

	local ssh_pid="$(tmux-get-ssh-pane-pid $(tmux-get-pane-id))"
	if [[ -z "$ssh_pid" ]]; then
		ssh_pid="\$PREV_PID"
	fi

	local prev_pane_id=$(tmux-get-pane-id)
	local pane_id=

	# Prevent collision with other outputs (eg. ssh login banner)
	local identifier="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)"

	log-msg $ssh_cmd

	# Outputs pid of newly split ssh session and the first ssh pid.
	# The first ssh pid is used to set the pid of first ssh pane.
	# See 'set-pane-pids' for more details.
	pane_id=$(tmux $split_cmd -PF "#{pane_id}" -c "#{pane_current_path}" $direction "$ssh_cmd -t '\
		PREV_PID=\$(pgrep -u \$USER \$(basename \$SHELL) | head -n 1); \
		cd -P /proc/$ssh_pid/cwd; \
		echo -e \"$identifier: \$\$ \$PREV_PID\"; \
		exec bash'; bash")

	set-pane-pids "$ssh_pid" "$prev_pane_id" "$pane_id" "$identifier"
}

unset LOG_FILE
#LOG_FILE=~/ssh_pane_log.txt

SPLIT_CMD="$1"
DIRECTION="$2"
SSH_CMD="$(tmux-get-pane-cmd)"

if [[ -z "$SSH_CMD" ]]; then
	exec tmux $SPLIT_CMD -c "#{pane_current_path}" $DIRECTION
	exit
fi

tmux-ssh-split "$SPLIT_CMD" "$DIRECTION" "$SSH_CMD"
clean-ssh-pane-pids
