unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

function s:source(file)
	if !empty(glob(a:file))
		exec "source " . a:file
	endif
endfunction

let data_dir = has('nvim') ? stdpath('data') . '/site' : $MYVIMDIR
if empty(glob(data_dir . '/autoload/plug.vim'))
	silent execute '!mkdir -p ' .data_dir.'/autoload/'
	silent execute '!wget -O '.data_dir.'/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

call s:source($MYVIMDIR . "vim-plug.vim")
call s:source($MYVIMDIR . "vim-plug-user.vim")

call plug#end()

function! s:set_readonly()
	if (&readonly)
		set nomodifiable
	else
		set modifiable
	endif
endfunction

" Airline
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ""
let g:airline_right_sep = ""

" Theme
set termguicolors
color catppuccin_macchiato

" Settings
set nomodeline
set number
set relativenumber

" Change viminfo filename
set viminfo='100,<50,s10,h,n~/.config/vim/.viminfo
filetype plugin indent on

" Indentation
set shiftwidth=4 smarttab
set tabstop=4 softtabstop=0

" Bell
set visualbell hidden
set t_vb=

" Mappings
noremap <C-a> <Nop>| " Fix tmux prefix key conflict
noremap <leader>i <C-a>

" Copy and paste from system clipboard
vnoremap <C-y> "+y
noremap <C-p> "+p

noremap ; :
noremap <silent> \rs :call <SID>strip_trailing_whitespace()<CR>

" Remove trailing whitespace
function! s:strip_trailing_whitespace()
	let v = winsaveview()
	silent! execute(':%s/\v\s+$//g')
	call winrestview(l:v)
endfunction

" Autocommands
augroup Autocommands
	autocmd!
	autocmd BufNewFile,BufRead *.tsx setlocal filetype=typescriptreact
	autocmd BufNewFile,BufRead *.jsx setlocal filetype=javascriptreact
	autocmd	BufWinEnter * call s:set_readonly()

	" Use :noa w[q] to write without stripping trailing whitespace
	autocmd BufWrite * call s:strip_trailing_whitespace()
	autocmd VimEnter *.c,*.h let g:filetype_h = "c"
augroup END

call s:source($MYVIMDIR . "functions.vim")
