unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

let data_dir = has('nvim') ? stdpath('data') . '/site' : $MYVIMDIR
if empty(glob(data_dir . '/autoload/plug.vim'))
	silent execute '!mkdir -p ' .data_dir.'/autoload/'
	silent execute '!wget -O '.data_dir.'/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

silent! source $MYVIMDIR/vim-plug.vim
silent! source $MYVIMDIR/vim-plug-user.vim

call plug#end()

function! s:set_readonly()
	if (&readonly)
		set nomodifiable
	else
		set modifiable
	endif
endfunction

" Airline
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ""
let g:airline_right_sep = ""

" Theme
set termguicolors
color catppuccin_macchiato

" Settings
set nomodeline
set number
set relativenumber

filetype plugin indent on

" Change history file locations
let $VIM_STATE = '~/.local/state/vim'
let &viminfo = "'100,<50,s10,h,n".$VIM_STATE."/.viminfo"
let g:netrw_home = $VIM_STATE.'/netrwhist'
unlet $VIM_STATE

" Indentation
set shiftwidth=4 smarttab
set tabstop=4 softtabstop=0

" Bell
set visualbell hidden
set t_vb=

" Mappings
noremap <C-a> <Nop>| " Fix tmux prefix key conflict
noremap <leader>i <C-a>

" Copy and paste from system clipboard
if (has("clipboard"))
	vnoremap <C-y> "+y
	noremap <C-p> "+p
endif

noremap ; :
noremap <silent> \rs :call <SID>strip_trailing_whitespace()<CR>

" Remove trailing whitespace
function! s:strip_trailing_whitespace()
	let v = winsaveview()
	silent! execute(':%s/\v\s+$//g')
	silent! call histdel('/', -1)
	call winrestview(l:v)
endfunction

" Autocommands
augroup Autocommands
	autocmd!
	autocmd BufNewFile,BufRead *.tsx setlocal filetype=typescriptreact
	autocmd BufNewFile,BufRead *.jsx setlocal filetype=javascriptreact
	autocmd BufNewFile,BufRead *.tmux setlocal filetype=tmux
	autocmd	BufWinEnter * call s:set_readonly()

	" Use :noa w[q] to write without stripping trailing whitespace
	autocmd BufWrite * call s:strip_trailing_whitespace()
	autocmd VimEnter *.c,*.h let g:filetype_h = "c"
augroup END

silent! source $MYVIMDIR/functions.vim
silent! source $MYVIMDIR/commands.vim
