#!/usr/bin/env bash

mkcd() {
	if (($# > 1)); then
		echo "${FUNCNAME[0]}: too many arguments" >&2
		return 1
	fi

	mkdir -p "$1" || return $?
	cd "$1" || return $?
}

# OSC 3008 escaping without external process. ~25x faster than sed equivalent.
__systemd_osc_context_escape() {
	local str="${1//\\/\\x5x}"
	echo "${str//;/\\x3b}"
}

# Shows the location of a function
wherefunc() (
	local func_name="$1"
	shopt -s extdebug

	if ! declare -F "$func_name"; then
		echo "${FUNCNAME[0]}: function '$func_name' not found" >&2
		return 1
	fi
)

# Rename a function
renamefunc() {
	local func_name="$1"
	local new_name=$2
	local func_def new_name_sanitized

	if (($# != 2)); then
		echo "usage: ${FUNCNAME[0]} function-name new-name" >&2
		return 1
	fi

	func_def=$(declare -f "$func_name")

	if [[ ! ${func_def-} ]]; then
		echo "${FUNCNAME[0]}: function '$func_name' not found" >&2
		return 1
	fi

	new_name_sanitized="${new_name//[^[:alnum:]-_]/}"

	if [[ "$new_name" != "$new_name_sanitized" ]]; then
		echo "${FUNCNAME[0]}: '$new_name' is not a valid function name" >&2
		return 1
	fi

	unset -f "$func_name"
	eval "${func_def/$current_name/$new_name}"
}

# Time a commnad with a desktop notification instead of outputting to stderr
time-notify() {
	local notify_time=1500
	local tmp notify_time
	local usage="usage: ${FUNCNAME[0]} [-t notify-time-ms] command [args...]"

	if [[ ! -f /usr/bin/time ]]; then
		/usr/bin/time
		return $?
	fi

	local OPTIND=1 OPTERR OPTARG opt
	while getopts "t:h" opt; do
		case "$opt" in
			t)
				notify_time=$OPTARG
				if ! ((notify_time > 0)); then
					echo "${FUNCNAME[0]}: invalid notify time '$OPTARG'" >&2
					return 1
				fi
				;;
			h)
				echo "$usage"
				return
				;;
			*)
				return 1
		esac
	done

	shift "$((OPTIND - 1))"

	if (($# == 0)); then
		echo "$usage" >&2
		return 1
	fi

	tmp="$(mktemp)" || return $?

	/usr/bin/time -f %E -o "$tmp" -- "$@"
	local exit_code=$?

	notify-send -t "$notify_time" -a "${FUNCNAME[0]}" "$*" "Finished in $(tail -n1 "$tmp")"
	rm "$tmp"

	return $exit_code
}
