#!/usr/bin/env bash

mkcd() {
	if [[ $# -gt 1 ]]; then
		echo "${FUNCNAME[0]}: too many arguments" >&2
		return 1
	fi

	mkdir -p "$1" || return $?
	cd "$1" || return $?
}

# OSC 3008 escaping without external process. ~25x faster than sed equivalent.
__systemd_osc_context_escape() {
	local str="${1//\\/\\x5x}"
	echo "${str//;/\\x3b}"
}

# Shows the location of a function
wherefunc() (
	local func_name="$1"
	shopt -s extdebug
	declare -F "$func_name" || {
		echo "${FUNCNAME[0]}: '$func_name' not found" >&2
		return 1
	}
)

# Rename a function
renamefunc() {
	local current_name="$1"
	local new_name=$2
	local func_def new_name_sanitized

	if (($# != 2)); then
		echo "usage: ${FUNCNAME[0]} function-name new-name" >&2
		return 1
	fi

	func_def=$(declare -f "$current_name")

	if [[ ! ${func_def-} ]]; then
		echo "${FUNCNAME[0]}: function '$current_name' not found" >&2
		return 1
	fi

	new_name_sanitized="${new_name//[^[:alnum:]-_]/}"

	if [[ "$new_name" != "$new_name_sanitized" ]]; then
		echo "${FUNCNAME[0]}: '$new_name' is not a valid function name" >&2
		return 1
	fi

	unset -f "$current_name"
	eval "${func_def/$current_name/$new_name}"
}

# Time a commnad with a desktop notification instead of outputting to stderr
time-notify() {
	if [[ ! -f /usr/bin/time ]]; then
		/usr/bin/time
		return $?
	fi

	local tmp notify_time
	tmp="$(mktemp)" || return $?
	notify_time="${NOTIFY_TIME:-1500}"

	/usr/bin/time -f %E -o "$tmp" -- "$@"
	local exit_code=$?

	local args="$*"
	notify-send -t "$notify_time" -a "${FUNCNAME[0]}" "$args" "Finished in $(tail -n1 "$tmp")"
	rm "$tmp"

	return $exit_code
}
